### ISSUE TITLE
Cannot import an AT lattice in pyAT

### ISSUE THREAD

**Issue by linahv** [atcollab/at#436]
Hi all, 

I have a lattice with AT cavities - so no harmonic number field, that I am saving from matlab but I cannot import in pyAT, either as a .mat or as .m. 

When loading a .mat, we get the following error message when it tries to load the cavity elements : 
`missing 1 required positional argument: 'energy' `

When loading a .m, all the RF cavities are skipped, and we get a warning : 
`Invalid line {0} skipped . `

When we added manually the harmonic number to the RF cavity line in the .m file, the cavity was properly loaded in pyAT.

**Comment by linahv** [comment]
[nom.txt](https://github.com/atcollab/at/files/9061734/nom.txt)

**Comment by linahv** [comment]
The test lattice we used to provoke the problem

**Comment by lfarv** [comment]
Hello @linahv 
Your lattice looks broken. If I load your nom.txt file in Matlab, I find the the RF cavities are crazy:

```
>> testring{147}

ans = 

  struct with fields:

       FamName: 'CAV_C05_01'
    PassMethod: 'RFCavityPass'
        Length: 0
         Class: 'RFCavity'
       Voltage: 500000
     Frequency: 3.523721693994240e+08
    HarmNumber: 992
       TimeLag: 0
        Energy: 6.000000000000000e+09
```
This one is correct, but:

```
>> testring{149}

ans = 

  struct with fields:

       FamName: 'CAV_C05_02'
    PassMethod: 'RFCavityPass'
        Length: 0
         Class: 'RFCavity'
       Voltage: 500000
     Frequency: 3.523721693994240e+08
    HarmNumber: 6.000000000000000e+09
       TimeLag: 0
        Energy: 'RFCavityPass'
```
this one has crazy parameters, as all the other ones. I do not know how you generated your cavities, but `atrfcavity` has mandatory `harmonicnumber` and `energy` arguments (5th and 6th arguments), so that the element structure has both `Energy` and `HarmNumber` fields. It's true that the `HarmNumber` field is no more used   (`Energy` is), but their presence is necessary. Don't remove these fields, and more generally used the element creation function (`atdrift`, `atrfcavity`,…) to create elements.

**Comment by lfarv** [comment]
The lines in the nom.txt file:
```
     atrfcavity('CAV_C05_01',0,500000,352372169.399424,992, 6000000000,'RFCavityPass');...
     atdrift('DR_45',1.06056,'EApertures',[0.032 0.004]);...
     atrfcavity('CAV_C05_02',0,500000,352372169.399424,6000000000,'RFCavityPass');...
```
Did you generated this with `atwritem` ? I do not understand why the 992 is missing on the 2nd cavity…

**Comment by linahv** [comment]
[nom.txt](https://github.com/atcollab/at/files/9083295/nom.txt)

Sorry Laurent, I must have sent the altered test file - we added the harmonic number in one cavity, to check if it was then recognise by pyAT while using at.load_m
This one comes directly from the AT lattice, no additional HarmNumber field in the RF cavities

**Comment by lfarv** [comment]
Hi, Lina. I still do not understand how you generated you `nom.m` file : when you create a cavity element with `atrfcavity`, it **has** a `HarmNumber` field. Did you remove it manually ? If you do, `atwritem` crashes if you try to generate a '.m' file. So how could you create this nom.m file ? In addition, if you try to load this file in Matlab, it does not crash, but the RF cavities are crazy:

```
>> ring{147}

ans = 

  struct with fields:

       FamName: 'CAV_C05_01'
    PassMethod: 'RFCavityPass'
        Length: 0
         Class: 'RFCavity'
       Voltage: 500000
     Frequency: 3.5237e+08
    HarmNumber: 6.0000e+09
       TimeLag: 0
        Energy: 'RFCavityPass'
```
So the answer is: your `nom. m` file is broken and cannot be used, neither in Matlab nor in python.

**Comment by lfarv** [comment]
Hi again. I cannot get the zip file. Apparently the link is empty… Please upload it again. Which version of AT are you using ? Did you try to load your .m file under Matlab, do you get something different from what I get above ?

**Comment by linahv** [comment]
[nominal_lattice.zip](https://github.com/atcollab/at/files/9090414/nominal_lattice.zip)

**Comment by linahv** [comment]
Ok, I guess the uploading failed in the previous attempt ! My apologies

**Comment by swhite2401** [comment]
@lfarv, I thought we had moved the harmonic number as a ring property as the cavity `passmethod` is not using it.
In which case, does it make sense to keep functions that require the harmonic number to be present in the cavity?

**Comment by lfarv** [comment]
@swhite2401: You are right, the harmonic number attribute of the cavities is not used any more. But the creation function for the cavity is, in Matlab:
```Matlab
atrfcavity(FamName,Length,Voltage,Frequency,HarmonicNumer,Energy,PassMethod,...)
```
or in python
```python
RFCavity(family_name: str, length: float, voltage: float,
                 frequency: float, harmonic_number: int, energy: float,
                 **kwargs)
```
So to create a cavity, you **have to** provide a value (anything) for the harmonic number, and it is stored as attribute. That's why the .m file provided by @linahv cannot work, neither in Matlab nor in python.

`at2str` in Matlab or `repr` in python, which create the text representation of a cavity, both print the harmonic number, taken from the (useless) attribute.

Changing the signature of the creation function is difficult because the harmonic number is not the last argument. It precedes the energy, which is mandatory. To consider the harmonic number as optional, one needs an assumption like: "if v is larger that 1000000, it is unlikely to be a harmonic number, so it must be the energy, and the harmonic number is missing". Relying on the argument type is not an option (both can usually fit in an integer). This can be done, or you may have a better idea…
